cc_test(
    name = "test_projection",
    srcs = ["test_projection.cpp"],
    deps = [
        "//:slam_core",
        "@googletest//:gtest_main",
    ],
    copts = [
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
)

cc_test(
    name = "test_robot_with_sensors",
    srcs = ["test_robot_with_sensors.cpp"],
    deps = [
        "//:slam_core",
        "@googletest//:gtest_main",
    ],
    copts = [
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
)

cc_test(
    name = "test_localization",
    srcs = ["test_localization.cpp"],
    deps = [
        "//:slam_core",
        "@googletest//:gtest_main",
    ],
    copts = [
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
)
