cc_test(
    name = "test_projection",
    srcs = ["test_projection.cpp"],
    deps = [
        "//:slam_core",
        "@googletest//:gtest_main",
    ],
    copts = [
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
)
